name: ACENET Container Trigger
on: [push]

jobs:
 build:
  name: SSH-Trigger
  runs-on: ubuntu-16.04
  steps:
   - name: Create and Deploy
     run: |
      mkdir -p ~/.ssh/
      ssh-keyscan -H services.dal.ace-net.ca >> ~/.ssh/known_hosts
      echo "${{ secrets.ACENET_KEY}}" > ~/.ssh/trigger
      chmod 600 ~/.ssh/trigger
      ssh -vvv -i ~/.ssh/trigger $SSH_USER@services.dal.ace-net.ca /opt/docker-deploy/trigger-push
      exit 0
     shell: bash
     env:
      SSH_USER: ${{ secrets.ACENET_USER }}
