name: ACENET Container Trigger
on: [push]

jobs:
 build:
  name: SSH-Trigger
  runs-on: ubuntu-latest
  steps:
   - name: Create and Deploy
     run: |
      mkdir -p ~/.ssh/
      cat <<EOF > ../acenet.key
      ${{ secrets.ACENET_KEY }}
      EOF
      sudo chmod 600 ../acenet.key
      ssh-keyscan -H services.dal.ace-net.ca >> ~/.ssh/known_hosts
      ssh -o HostKeyAlgorithms=ecdsa-sha2-nistp256 -i $SSH_KEY_PATH $SSH_USER@services.dal.ace-net.ca /opt/docker-deploy/trigger-push
     shell: bash
     env:
      SSH_KEY_PATH: ${{ github.workspace }}/../acenet.key
      SSH_USER: ${{ secrets.ACENET_USER }}
